//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lecture_fichier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Importation_PR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Importation_PR()
        {
            this.Prelevements_Consolides = new HashSet<Prelevements_Consolides>();
            this.Reglements_Consolides = new HashSet<Reglements_Consolides>();
        }
    
        public long Id_Imp { get; set; }
        public string Code_Entite { get; set; }
        public Nullable<System.DateTime> Date_Importation { get; set; }
        public string Mois { get; set; }
        public string Annee { get; set; }
        public string Type_Peche { get; set; }
        public string Code_Correspondance { get; set; }
        public string Desig_Correspondance { get; set; }
        public string Num_Envoi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prelevements_Consolides> Prelevements_Consolides { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reglements_Consolides> Reglements_Consolides { get; set; }
    }
}
