//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lecture_fichier
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConsoCNSSEntities : DbContext
    {
        public ConsoCNSSEntities()
            : base("name=ConsoCNSSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Importation_PR> Importation_PR { get; set; }
        public virtual DbSet<Prelevements_Consolides> Prelevements_Consolides { get; set; }
        public virtual DbSet<Reglements_Consolides> Reglements_Consolides { get; set; }
    }
}
