//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lecture_fichier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prelevements_Consolides
    {
        public decimal Id_PC { get; set; }
        public Nullable<long> Id_Imp { get; set; }
        public Nullable<System.DateTime> Date_Exploitation { get; set; }
        public string Code_Bateau { get; set; }
        public string Nom_Bateau { get; set; }
        public string Type_Bateau { get; set; }
        public string Num_Declaration { get; set; }
        public Nullable<double> Mnt_Vente { get; set; }
        public Nullable<double> Mnt_Brut_Operation { get; set; }
        public Nullable<double> Mnt_COM { get; set; }
        public Nullable<double> Mnt_TVA { get; set; }
        public double Mnt_Net_Operation { get; set; }
    
        public virtual Importation_PR Importation_PR { get; set; }
    }
}
