//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lecture_fichier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reglements_Consolides
    {
        public decimal Id_Reg { get; set; }
        public Nullable<long> Id_Imp { get; set; }
        public string Num_OV { get; set; }
        public string Banque { get; set; }
        public string Agence { get; set; }
        public Nullable<double> Mnt_OV { get; set; }
        public Nullable<System.DateTime> Date_OV { get; set; }
        public string Num_Envoi_Prelevement { get; set; }
    
        public virtual Importation_PR Importation_PR { get; set; }
    }
}
